# Site settings
title:       Stefano Marzorati
email:       your_email@example.com
author:      Stefano Marzorati
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://kasper.marzorati.co"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: stefanomarzorati

# Social icons
show_social_icons: true
github_username:
stackoverflow_id:
twitter_username: marzorati_ste
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
