# Site settings
title:       Stefano Marzorati
email:       stefano@marzorati.co
author:      Stefano Marzorati
description: "IT Manager - Addicted to new technology and lead away by innovation."
baseurl:     ""
url:         "http://marzorati.co"
date_format: "%-d %b, %Y"

# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]

# Google analytics
google_analytics: UA-38247823-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
# disqus_shortname: stefanomarzorati

# Social icons
show_social_icons: true
github_username: marste
twitter_username: marzorati_ste
linkedin_username: stefanomarzorati
instagram_username: stefanomarzorati
# soundcloud_username: marste
# google_plus_id: +StefanoMarzorati
# bitcoin_url:
# stackoverflow_id:
# paypal_url:
# flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-sitemap